queue_rules:
  - name: default
    queue_conditions:
      - author=dwolla-oss-scala-steward[bot]
      - status-success=Build and Test (ubuntu-latest, 2.12, temurin@11)
      - status-success=Build and Test (ubuntu-latest, 2.12, temurin@8)
    merge_conditions:
      - status-success=Build and Test (ubuntu-latest, 2.12, temurin@11)
      - status-success=Build and Test (ubuntu-latest, 2.12, temurin@8)
    merge_method: squash

pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=dwolla-oss-scala-steward[bot]
    actions:
      label:
        add: [dependency-update]
  - name: automatic update pull requests
    conditions:
      - author=dwolla-oss-scala-steward[bot]
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
  - name: merge scala-steward's PRs
    conditions: []
    actions:
      queue:
