package com.dwolla.sbt.docker.model

import reified.DockerStartReifiedCommandLineArguments

case class DockerStartArguments(containerName: String) extends DockerProcessReifiedCommandLineArgumentBuilder[DockerStartReifiedCommandLineArguments]{
  override def toDockerProcessReifiedCommandLineArguments = DockerStartReifiedCommandLineArguments(containerName)
}
